/*
   CREATE INDEX ID_OBSERVACAO ON CLIENTE  -- "Indice com campo do tipo TEXT"  
   USING GIN OBS(GIN_TRMN_ID);

   CREATE INDEX ID_CONTAS ON CONTASRECEBER (VENCIMENTO, VALOR); -- "Indice composto, normalmente usado quando a chave primaria composta"
	
*/

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL,
	NOME VARCHAR(200) NOT NULL,
	TELEFONE INT NOT NULL,
	CPF INT NOT NULL,
	PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE VENDA (
	IDVENDA INT NOT NULL,
	IDCLIENTE INT NOT NULL,
	DATAVENDA DATE NOT NULL,
	VALORVENDA NUMERIC(8,2) NOT NULL,
	PRIMARY KEY (IDVENDA,IDCLIENTE),
	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE CONTAS_RECEBER (
	IDCONTA INT NOT NULL,
	IDCLIENTE INT NOT NULL,
	IDPARCELA INT NOT NULL,
	DATACONTA DATE NOT NULL,
	VENCIMENTO DATE NOT NULL,
	VALOR NUMERIC(8,2) NOT NULL,
	PRIMARY KEY (IDCONTA, IDCLIENTE, IDPARCELA),
	FOREIGN KEY (IDVENDA) REFERENCES VENDA(IDVENDA),
	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

INSERT AI

